version: "2.3"
services:
  rp1:
    hostname: rp1
    image: ${VIZIX_BRIDGES_IMAGE}
    environment:
      VIZIX_ESPER: 'no'
      VIZIX_BRIDGE_TYPE: rulesprocessor
      VIZIX_KAFKA_CODE: RulesProcessor
      VIZIX_KAFKA_SERVERS: $KAFKA_SERVERS
    volumes:
      - ./volume/vizix/rp1:/var/vizix

  rp2:
    hostname: rp2
    image: ${VIZIX_BRIDGES_IMAGE}
    environment:
      VIZIX_ESPER: 'no'
      VIZIX_BRIDGE_TYPE: rulesprocessor
      VIZIX_KAFKA_CODE: RulesProcessor
      VIZIX_KAFKA_SERVERS: $KAFKA_SERVERS
    volumes:
      - ./volume/vizix/rp2:/var/vizix

  rp3:
    hostname: rp3
    image: ${VIZIX_BRIDGES_IMAGE}
    environment:
      VIZIX_ESPER: 'no'
      VIZIX_BRIDGE_TYPE: rulesprocessor
      VIZIX_KAFKA_CODE: RulesProcessor
      VIZIX_KAFKA_SERVERS: $KAFKA_SERVERS
    volumes:
      - ./volume/vizix/rp3:/var/vizix

  rp4:
    hostname: rp4
    image: ${VIZIX_BRIDGES_IMAGE}
    environment:
      VIZIX_ESPER: 'no'
      VIZIX_BRIDGE_TYPE: rulesprocessor
      VIZIX_KAFKA_CODE: RulesProcessor
      VIZIX_KAFKA_SERVERS: $KAFKA_SERVERS
    volumes:
      - ./volume/vizix/rp4:/var/vizix

  mi1:
    image: ${VIZIX_BRIDGES_IMAGE}
    environment:
      VIZIX_CORE_CODE: MongoInjector
      VIZIX_BRIDGE_TYPE: mongoingestor
      VIZIX_KAFKA_SERVERS: $KAFKA_SERVERS
    volumes:
      - ./volume/vizix/mi1:/var/vizix

  mi2:
    image: ${VIZIX_BRIDGES_IMAGE}
    environment:
      VIZIX_CORE_CODE: MongoInjector
      VIZIX_BRIDGE_TYPE: mongoingestor
      VIZIX_KAFKA_SERVERS: $KAFKA_SERVERS
    volumes:
      - ./volume/vizix/mi2:/var/vizix

  mi3:
    image: ${VIZIX_BRIDGES_IMAGE}
    environment:
      VIZIX_CORE_CODE: MongoInjector
      VIZIX_BRIDGE_TYPE: mongoingestor
      VIZIX_KAFKA_SERVERS: $KAFKA_SERVERS
    volumes:
      - ./volume/vizix/mi3:/var/vizix

  mi4:
    image: ${VIZIX_BRIDGES_IMAGE}
    environment:
      VIZIX_CORE_CODE: MongoInjector
      VIZIX_BRIDGE_TYPE: mongoingestor
      VIZIX_KAFKA_SERVERS: $KAFKA_SERVERS
    volumes:
      - ./volume/vizix/mi4:/var/vizix

  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./volume/zookeeper-data/data:/data
      - ./volume/zookeeper-data/datalog:/datalog

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $THIS_IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$THIS_IP:9092
      KAFKA_ZOOKEEPER_CONNECT: $ZOOKEEPER_IP:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      #KAFKA_BROKER_ID: 1
    volumes:
      - ./volume/kafka/logs:/kafka/kafka-logs-kafka

  datadog:
    restart: always
    image: datadog/docker-dd-agent:12.4.5190
    hostname: datadog
    container_name: datadog
    environment:
      API_KEY: 5dfd1422b74a1c79b13980c621df73af
      SD_BACKEND: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /opt/vizix/dd/:/conf.d/d


